/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "convert.h"

int *
convert_hex_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int n = *argp;
	char buf[10];
	snprintf(buf, 11, "%x", n);
	printf("Hexadecimal: %s\n", buf);
	result = strtol(buf, NULL, 16);
	return &result;
}

int *
convert_oct_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int n = *argp;
	char buf[10];
	snprintf(buf, 11, "%o", n);
	printf("Octal: %s\n", buf);
	result = strtol(buf, NULL, 8);
	return &result;
}
